### ISSUE TITLE
缺少iov 包

### ISSUE THREAD

**Issue by ityida** [zqingxi/gbt32960#1]
作者你好，你的gbt32960项目我想学习下，但是下载下来发现缺少一个 iov 包，您方便提供下吗？17625341118这是我的手机号码，希望您的回复。非常感谢！

**Comment by zqingxi** [comment]
您好，能贴一下具体的错误提示吗？这个项目不需要iov包啊

**Comment by zqingxi** [comment]
> 作者你好，你的gbt32960项目我想学习下，但是下载下来发现缺少一个 iov 包，您方便提供下吗？17625341118这是我的手机号码，希望您的回复。非常感谢！

您好，能贴一下具体的错误提示吗？这个项目不需要iov包啊

**Comment by activemax** [comment]
遇到同样的问题：

com.ime.iov.gbt32960 这个包找不到

在启动 InfoServerApplication 这个类的时候报错：

![image](https://user-images.githubusercontent.com/2849142/59412355-d31b6980-8def-11e9-84cb-3dbde85b7c4d.png)

**Comment by ityida** [comment]
> > 作者你好，你的gbt32960项目我想学习下，但是下载下来发现缺少一个 iov 包，您方便提供下吗？17625341118这是我的手机号码，希望您的回复。非常感谢！
> 
> 您好，能贴一下具体的错误提示吗？这个项目不需要iov包啊

gbt32960-protocol/src/main/java/com/ime/gbt32960/protocol/ProtocolHandler.java这个文件里缺少包
import com.ime.iov.gbt32960.LoginRequest;
import com.ime.iov.gbt32960.PlatformMessage;
import com.ime.iov.gbt32960.ProtoResponse;
import com.ime.iov.gbt32960.TerminalClockCorrect;

**Comment by zqingxi** [comment]
您们好，具体配置操作步骤见下图：
![image](https://user-images.githubusercontent.com/14819015/59421773-bc7e0e00-8e01-11e9-8267-2434016a9027.png)

**Comment by ityida** [comment]
非常感谢！问题已解决！
