### ISSUE TITLE
请问这个项目如何打包？

### ISSUE THREAD

**Issue by activemax** [zqingxi/gbt32960#2]
你好，请问一下这个项目如何打成jar或者war包运行？

试了一下用idea打出来的jar包无法运行，提示：

![image](https://user-images.githubusercontent.com/2849142/59480841-c1d86880-8e94-11e9-946b-3f2bd229ac38.png)

求帮助，感谢！

**Comment by zqingxi** [comment]
您好，请参考 https://my.oschina.net/u/2505383/blog/677301

**Comment by activemax** [comment]
@zqingxi 谢谢
